[package]
name = "heartrate_tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
heartrate_core.workspace = true

btleplug = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
color-eyre = { workspace = true }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
